### ISSUE TITLE
Send isnt working on my bot

### ISSUE THREAD

**Issue by Duued** [dragdev-studios/RiftGun#1]
Send isn't working in my bot, 
![image](https://user-images.githubusercontent.com/66633587/91641923-5cb75700-e9f5-11ea-9183-bc38d3bb95fd.png)
and it has send message permissions in the select channel as you can see 
![image](https://user-images.githubusercontent.com/66633587/91641937-6e006380-e9f5-11ea-91c9-1da0505c7f30.png)

**Comment by timedoutuk** [comment]
Please include basically any more information that can be useful, e.g error logs, jsk dbg, etc
