### ISSUE TITLE
Send isn't working and when I try using Jsk to debug it, it says the command isn't found

### ISSUE THREAD

**Issue by Duued** [dragdev-studios/RiftGun#2]
![image](https://user-images.githubusercontent.com/66633587/91642107-9c327300-e9f6-11ea-8c11-cdef88190280.png)

**Comment by timedoutuk** [comment]
Are you sure you have the right version?

**Comment by Duued** [comment]
How do i update the version after uploading it with Jishaku?

**Comment by timedoutuk** [comment]
See README.md

**Comment by Duued** [comment]
![image](https://user-images.githubusercontent.com/66633587/91642172-24b11380-e9f7-11ea-9a98-8e3eaca3d8a1.png)

**Comment by timedoutuk** [comment]
`pip[3] install <project> --user --upgrade`

**Comment by Duued** [comment]
ok now a separate issue  
![image](https://user-images.githubusercontent.com/66633587/91642225-9a1ce400-e9f7-11ea-9232-306ac65b7200.png)

**Comment by timedoutuk** [comment]
Install the missing packages then

**Comment by Duued** [comment]
![image](https://user-images.githubusercontent.com/66633587/91642369-c38a3f80-e9f8-11ea-9a69-fe47738e6188.png)

**Comment by timedoutuk** [comment]
What is this

**Comment by Duued** [comment]
i tried to install and run that package, thats the error it gave

**Comment by timedoutuk** [comment]
why are you trying to run the package?

**Comment by Duued** [comment]
I thought i was supposed to...

**Comment by timedoutuk** [comment]
No, I said **install**, not **load**. The module handles all that for you.

**Comment by Duued** [comment]
![image](https://user-images.githubusercontent.com/66633587/91642463-925e3f00-e9f9-11ea-8541-eaf5e32c481d.png)

**Comment by timedoutuk** [comment]
Patched in most recent update
