### ISSUE TITLE
cant view apply's 

### ISSUE THREAD

**Issue by GmGnagZ** [dragdev-studios/RiftGun#3]
Well i am the owner and it says i am not the owner but i completely own the server

**Comment by zanderp25** [comment]
You have to be the owner of the bot.

**Comment by zanderp25** [comment]
Also what do you mean by “apply’s”

**Comment by GmGnagZ** [comment]
but why tho

**Comment by GmGnagZ** [comment]
i mean i started an applications for mods so people can apply but when i come to open them it says ur not the owner

**Comment by zanderp25** [comment]
RiftGun does not have applications. Do you mean YourApps?

**Comment by GmGnagZ** [comment]
yes

**Comment by GmGnagZ** [comment]
YourApps bot

**Comment by zanderp25** [comment]
To review applications, you must do ‘ya?review’. To join the support server, you can go to https://discord.gg/T9u3Qcm

**Comment by GmGnagZ** [comment]
thank you i use ya?open applications

**Comment by zanderp25** [comment]
I see

**Comment by timedoutuk** [comment]
[You probably want to be here instead of an unrelated GitHub repository](https://addhq.xyz/s/ya)
